name: travel_app
description: A new Flutter application for travel planning and exploration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.0
  image_picker: ^1.0.7
  flutter_dotenv: ^5.1.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  http: ^1.2.0
  url_launcher: ^6.2.0
  shared_preferences: ^2.2.2
  visibility_detector: ^0.4.0+2
  share_plus: ^10.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
